apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: chirpingcanary-co-uk-tls
spec:
  secretName: chirpingcanary-co-uk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: chirpingcanary.co.uk
  dnsNames:
    - chirpingcanary.co.uk
    - www.chirpingcanary.co.uk
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - chirpingcanary.co.uk
          - www.chirpingcanary.co.uk
